spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: ap01
    password: 0911
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#    cash-enabled: false
#    local-cache-scope: STATEMENT
  config-location: classpath:config/mybatis/mybatis-plugins.xml
  mapper-locations: classpath:mapper/**/*.xml