spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: ap01
    password: 0911
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379

#springdoc:
#  version: '@springdoc.version@'
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#  show-actuator: true
#  group-configs:
#  - group: stores
#    paths-to-match: /user/**
#  - group: users
#    packages-to-scan: com.mysql.mybatis.test.demo

mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    lazy-loading-enabled: true
#    cash-enabled: false
#    local-cache-scope: STATEMENT
  config-location: classpath:config/mybatis/mybatis-plugins.xml
  mapper-locations: classpath:mapper/**/*.xml